### ISSUE TITLE
Packaging for Debian Buster

### ISSUE THREAD

**Issue by rgarrigue** [rabbitmq/rabbitmq-server-release#112] opened 2019-10-28 09:34 UTC
Can you please package rabbitmq-server for Debian Buster, so it's available in [bintray](https://bintray.com/rabbitmq/debian/rabbitmq-server) ?

I'm aware of the existance of a package from Debian maintainers. But 3.8 isn't available. And there's a little issue with this one, it renames rabbitmq.conf to rabbitmq-env.conf on installation, which prevent setting config files before package installation, the way I tried first while setting up cluster via dicovery.

**Comment by michaelklishin** [comment] 2019-10-28 10:26
Duplicate of #107.

**Closed as completed by michaelklishin** 2019-10-28 10:26 UTC
Labels: duplicate

**Comment by michaelklishin** [comment] 2019-10-28 10:30
Our [Debian guide](https://www.rabbitmq.com/install-debian.html#apt-bintray) now explains that there is no "package for Buster", the package is exactly the same for all distributions. You can specify `bionic` for distribution name and it would install exactly the same `.deb`.

Buster will be an indexed distribution on Bintray when `3.8.1` is out. It is already the case [on Package Cloud](https://packagecloud.io/rabbitmq/rabbitmq-server/packages/debian/buster/rabbitmq-server_3.7.20-1_all.deb) and [on Bintray](https://bintray.com/rabbitmq/debian/rabbitmq-server/3.7.20-1#files/dists%2Fbuster) for the 3.7 series starting with 3.7.20.
